FROM python:3

WORKDIR /python-docker
COPY mongo_tests.py mongo_tests.py
COPY requirements.txt requirements.txt
COPY db_constants.py db_constants.py

RUN pip install -r requirements.txt

CMD [ "python", "./mongo_tests.py" ]