FROM python:3

WORKDIR /python-docker
COPY tables_csv tables_csv
COPY requirements.txt requirements.txt
COPY database_initialize.py database_initialize.py

RUN pip install -r requirements.txt

CMD [ "python", "./database_initialize.py" ]