version: '3.8'
services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
  database_inizializer:
    container_name: database_inizializer
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile_db_inizializer
    image: database_inizializer:latest
  database_tests:
    container_name: database_tests
    depends_on:
      - postgres_db
      - database_inizializer
    build:
      context: .
      dockerfile: Dockerfile_db_tests
    image: database_tests:latest

volumes:
  db:
    driver: local