FROM python:3

WORKDIR /python-docker
COPY postgresql_queries postgresql_queries
COPY database_initialize.py database_initialize.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD [ "python", "./database_initialize.py" ]