FROM python:3

WORKDIR /python-docker
COPY main.py main.py
COPY requirements.txt requirements.txt
COPY db_constants.py db_constants.py

RUN pip install -r requirements.txt

CMD [ "python", "./main.py" ]